include_directories(${OPENQASM_INCLUDE_DIR})
include_directories(${CMAKE_CURRENT_BINARY_DIR})
include_directories(${CMAKE_CURRENT_SOURCE_DIR})

set(OPENQASM_LOWERING_SOURCES
  ASTToPulse.cpp
)

set(PHYSICAL_LIB_NAME "qasmLowering")

if(BUILD_SHARED_LIBS)
  add_library(${OPENQASM_TARGET_LOWERING_SHARED}
    SHARED
    ${OPENQASM_LOWERING_SOURCES}
  )

  set_target_properties(${OPENQASM_TARGET_LOWERING_SHARED} PROPERTIES
    OUTPUT_NAME ${PHYSICAL_LIB_NAME}
    POSITION_INDEPENDENT_CODE ON
  )

  target_link_libraries(${OPENQASM_TARGET_LOWERING_SHARED} PUBLIC
    ${OPENQASM_TARGET_AST_SHARED}
    ${OPENQASM_TARGET_PULSE_IR_SHARED}
  )

  target_compile_features(
    ${OPENQASM_TARGET_LOWERING_SHARED}
    PUBLIC
    ${REQUIRED_FEATURES}
  )
endif()

if(BUILD_STATIC_LIBS)
  add_library(${OPENQASM_TARGET_LOWERING_STATIC}
    STATIC
    ${OPENQASM_LOWERING_SOURCES}
  )

  set_target_properties(${OPENQASM_TARGET_LOWERING_STATIC} PROPERTIES
    OUTPUT_NAME ${PHYSICAL_LIB_NAME}
    POSITION_INDEPENDENT_CODE ON
  )

  target_link_libraries(${OPENQASM_TARGET_LOWERING_STATIC} PUBLIC
    ${OPENQASM_TARGET_AST_STATIC}
    ${OPENQASM_TARGET_PULSE_IR_STATIC}
  )

  target_compile_features(
    ${OPENQASM_TARGET_LOWERING_STATIC}
    PUBLIC
    ${REQUIRED_FEATURES}
  )
endif()